### ISSUE TITLE
Doubts about the sample poison

### ISSUE THREAD

**Issue by moyudely** [alewarne/MachineUnlearning#3]
I would be very grateful if you could guide me to run the example poison.I did not find deletion related operations in the poison folder. In other words, how should I get repaired_model.hdf5？My email is lyzdc123@gmail.com and I would be grateful for any guidance from you.

**Comment by alewarne** [comment]
We are currently working on a few jupyter notebooks to show how the code should be used. Stay tuned!

**Comment by moyudely** [comment]
OK，thanks a lot.

**Comment by alewarne** [comment]
It has just been added, enjoy!
