### ISSUE TITLE
How to find Pipeline_classes?

### ISSUE THREAD

**Issue by ZhouRongqi** [alewarne/MachineUnlearning#4]
Dear author,I want to know how to find Pipeline_classes documents? there are no answers on internet. Thank you and have a good day!

**Comment by ZhouRongqi** [comment]
the Pipeline_classes is used in data_to_arr.py.

**Comment by alewarne** [comment]
I added the file, thanks!

**Comment by ZhouRongqi** [comment]
> I added the file, thanks!
I am very glad that you can reply  my message. Also, I can't find the category_dict_adult.pkl file under the Adult file that needs to be loaded in the DataLoader.py. Could you upload it?Thank you very much!

**Comment by ZhouRongqi** [comment]
> I added the file, thanks!

I am very glad that you can reply my message. Also, I can't find the category_dict_adult.pkl file under the Adult file that needs to be loaded in the DataLoader.py. Could you upload it?Thank you very much!
