### ISSUE TITLE
posion unlearning update only adpoted in a hvp_batch_size

### ISSUE THREAD

**Issue by CoderHHX** [alewarne/MachineUnlearning#8]
Hi @alewarne , thanks for your insightful work and code sharing. When I read the codes, I found that for the poison unlearning parts, both first-order and second-order unlearning updates only run in a hvp_batch https://github.com/alewarne/MachineUnlearning/blob/1968fd604147887b69f1adc9d808904fb02498d8/Applications/Poisoning/unlearn/common.py#LL99C9-L99C9. 
What if the whole changed size is far larger than hvp_batch, i,e., len(dedelta_idx) >> hvp_batch_size? In this case, a 1024 or 512-size unlearning update may not work well.

**Comment by alewarne** [comment]
Hi,

not sure if I get your question right: Firstly, a general insight of our paper is that the accuracy of the update gets worse if the size of delta rises (see Figure 9 in the [paper](https://arxiv.org/pdf/2108.11577.pdf). However, the update can be calculated if the hvp_batch_size is smaller than the total number of points to change, in this case the update is repeatedly applied until convergence of the LISSA algorithm. Does this answer your question?

**Comment by CoderHHX** [comment]
Thanks for your reply! I now understand this operation.
